package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/build_rules:genproto.bzl", "proto_java_library")

proto_java_library(
    name = "proto_dash",
    src = "dash.proto",
)
