package(default_visibility = ["//visibility:public"])

load("@bazel_tools//tools/build_rules:genproto.bzl", "java_proto_library")

java_proto_library(
    name = "proto_dash",
    src = "dash.proto",
)
